name: Next.js and CDK Build Check

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify Node.js version compatible with both Next.js and CDK

      # Step 3: Install dependencies for Next.js
      - name: Install dependencies for Next.js
        run: npm install

      # Step 4: Create amplify_outputs.json with an empty JSON object
      - name: Create amplify_outputs.json
        run: echo '{}' > amplify_outputs.json

      # Step 5: Build Next.js project
      - name: Build Next.js
        run: npm run build

      # Step 6: Run Next.js linting (optional but recommended)
      - name: Lint Next.js project
        run: npm run lint

      # Step 7: Install AWS CDK CLI globally
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # Step 8: Install dependencies for CDK (inside the cdk folder)
      - name: Install dependencies for CDK
        working-directory: cdk
        run: npm install

      # Step 9: Synthesize CDK app to check for compilation issues
      - name: Run CDK Synth
        working-directory: cdk
        run: cdk synth
